exercise_html_purifier:
    default_cache_serializer_path: '%kernel.cache_dir%/htmlpurifier'
    html_profiles:
        default:
            config:
                Core.Encoding: 'UTF-8'
        summary:
            config:
                HTML.ForbiddenElements: ['a']

