hwi_oauth:
    firewall_names: ['main']
    use_referer: true
    target_path_parameter: _destination
    fosub:
        properties:
            ssp: 'ssp_id'
    resource_owners:
        ssp:
            type: 'oauth2'
            class: 'App\Security\Core\User\OAuth2SimpleSAMLphpResourceOwner'
            client_id: '%env(CLIENT_ID)%'
            client_secret: '%env(CLIENT_SECRET)%'

services:
    my.oauth_aware.user_provider.service:
        class: 'App\Security\Core\User\OAuth2SimpleSAMLphpUserProvider'
        arguments: [ '@fos_user.user_manager', { ssp: 'ssp_id' } ]
