ivory_ck_editor:
    default_config: simple_toolbar
    configs:
        simple_toolbar:
            basicEntities: false
            entities_greek: false
            entities_latin: false
            entities_additional: ''
            fillEmptyBlocks: false
            tabSpaces: 0
            toolbar:
                - ['Bold', 'Italic', 'Strike', 'Link']
                - ['BulletedList', 'NumberedList', '-', 'Outdent', 'Indent']
                - ['Copy', 'Paste', 'PasteFromWord', '-', 'Undo', 'Redo']
                - ['Source']
