framework:
    messenger:
        transports:
        # Uncomment the following line to enable a transport named "amqp"
        # amqp: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
        # Route your messages to the transports
        # 'App\Message\YourMessage': amqp

        buses:
            messenger.bus.commands:
                middleware:
                    # Using the default configured entity manager name
                    - doctrine_transaction
            messenger.bus.queries: ~
            messenger.bus.events:
                middleware:
                    # Using the default configured entity manager name
                    - doctrine_transaction
