sonata_admin:
    security:
        role_admin: ROLE_ADMIN
        role_super_admin: ROLE_SUPER_ADMIN
    templates:
        # default global templates
        layout:  '/backend/standard_layout.html.twig'
    title: Ideas
    title_logo: 'assets/images/ideas-small.png'
    options:
        title_mode: 'single_image'
    dashboard:
        groups:
            app.admin.resources:
                label: 'group.resources'
                label_catalogue: 'messages'
                icon: '<i class="fa fa-database"></i>'
                items:
                - 'eco.admin.activity'
                - 'eco.admin.idea'
                - 'eco.admin.degree'
                roles:
                    - 'ROLE_ADMIN'
            app.admin.messages:
                label: 'group.messages'
                label_catalogue: 'messages'
                icon: '<i class="fa fa-telegram"></i>'
                items:
                - 'eco.admin.telegram_chat_private'
                - 'eco.admin.telegram_chat_super_group'
                - 'eco.admin.telegram_chat_group'
                - 'eco.admin.telegram_chat_channel'
                roles:
                    - 'ROLE_SUPER_ADMIN'
            app.admin.user:
                label: 'sonata_user'
                label_catalogue: 'SonataUserBundle'
                icon: '<i class="fa fa-users"></i>'
                items:
                - 'sonata.user.admin.user'
                - 'sonata.user.admin.group'
                roles:
                    - 'ROLE_SUPER_ADMIN'

sonata_block:
    default_contexts: ['cms']
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   ['admin']
        sonata.admin.block.search_result:
            contexts:   ['admin']
        # Your other blocks
        sonata.block.service.text:
        sonata.block.service.inactive:
