tactician:
    commandbus:
        default:
            middleware:
             - tactician.middleware.locking
             - tactician.middleware.validator
             - tactician.middleware.doctrine
             - tactician.middleware.command_handler
