vich_uploader:
    db_driver: orm

    mappings:
        avatars:
            uri_prefix: /images/avatars
            upload_destination: '%kernel.project_dir%/public/images/avatars'
            namer:              vich_uploader.namer_uniqid

            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true